spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
